### ISSUE TITLE
手势滑动返回时，导致一个小bug

### ISSUE THREAD

**Issue by codermurphy** [wlgemini/SwiftyNavigationBar#1]
如果当前controller的状态栏是白色，
上一个controller的状态是黑色
在手势滑动pop的时候，会导致状态栏一半黑，一半白
目前我的解决方案是在 proxy.swift 中的navigationcontroller代理中
....
 guard let preferenceStyle = navBar.preferenceStyle else { return }
navBar.setStyle(viewController.snb) 新增部分
......
如果有更好的方案请回复下

**Comment by wlgemini** [comment]
你好，应该是不需要这么设置的，vc.snb的相关设置优先级最高。如果上一个vc.snb没有设置相关属性，就会用preference的，不然就用默认设置了。你应该修改一下UINavigationController.init中的preference配置
