### ISSUE TITLE
可以支持LargeTitle模式吗？

### ISSUE THREAD

**Issue by wwdc14yh** [wlgemini/SwiftyNavigationBar#3]
RT

**Comment by wwdc14yh** [comment]
还有delegate不会主动调用
`@available(iOS 7.0, *)
    optional func navigationController(_ navigationController: UINavigationController, interactionControllerFor animationController: UIViewControllerAnimatedTransitioning) -> UIViewControllerInteractiveTransitioning?`
` @available(iOS 7.0, *)
    optional func navigationController(_ navigationController: UINavigationController, animationControllerFor operation: UINavigationController.Operation, from fromVC: UIViewController, to toVC: UIViewController) -> UIViewControllerAnimatedTransitioning?`
这个两个方法

**Comment by wlgemini** [comment]
可以有LargeTitle的，只是背景会变大。

**Comment by wlgemini** [comment]
proxy都是消息转发了，按理说你实现这几个方法就应该有调用的。proxy只拦截了一个delegate的方法。

**Comment by wwdc14yh** [comment]
关于第二问题，如果按照demo里这样写的话，那两个delegate确实不会被转发出来。
因为你设置`self._navigationController.delegate = self` 转场那两个代理方法会被调用一次。但是在`Proxy`类中的`navigationControllerDelegate`属性此时还是nil。点击push 的时候转场方法也不会被调用。但是重设`self._navigationController.delegate`转场的那两个方法会被调用。。这是我测试出来的，希望能有帮助！

我目前在`navigationControllerDelegate`属性的didSet Closer 里写了如下代码
```
guard let _ = navigationControllerDelegate else {return}
self._navigationController.delegate = nil
self._navigationController.delegate = self
```
但是在`self.navigationControllerDelegate?.responds(to: aSelector)` 方法中始终返回false... 很无语

**Comment by wlgemini** [comment]
好的，记下了👌

**Comment by wlgemini** [comment]
主要修改了SwiftyNavigationBar.navigationControllerDelegate的setter实现，应该就有调用了。你用的时候不需要做什么改动。
不调用的原因：在设置`UINavigationController.delegate`时，`UINavigationController`内部遍历了所有的`delegate`方法是否响应，之后就把这个状态缓存起来了。从新设置一下`delegate`为`nil`可以情况这个状态缓存。

**Comment by wlgemini** [comment]
bug会在下一个小版本中修复
